dotnet pack Bjd.Common -o .. -c %Configuration%
dotnet pack Bjd.DhcpServer -o .. -c %Configuration%
dotnet pack Bjd.DnsServer -o .. -c %Configuration%
dotnet pack Bjd.FtpServer -o .. -c %Configuration%
dotnet pack Bjd.Pop3Server -o .. -c %Configuration%
dotnet pack Bjd.ProxyFtpServer -o .. -c %Configuration%
dotnet pack Bjd.ProxyHttpServer -o .. -c %Configuration%
dotnet pack Bjd.ProxyPop3Server -o .. -c %Configuration%
dotnet pack Bjd.ProxySmtpServer -o .. -c %Configuration%
dotnet pack Bjd.ProxyTelnetServer -o .. -c %Configuration%
dotnet pack Bjd.SmtpServer -o .. -c %Configuration%
dotnet pack Bjd.TftpServer -o .. -c %Configuration%
dotnet pack Bjd.TunnelServer -o .. -c %Configuration%
dotnet pack Bjd.WebApiServer -o .. -c %Configuration%
dotnet pack Bjd.WebServer -o .. -c %Configuration%
